### ISSUE TITLE
Project is incorrectly named

### ISSUE THREAD

**Issue by cvrebert** [Nerian/bootstrap-typeahead-rails#2]
This project wraps https://github.com/twitter/typeahead.js , which has *never been a part of [Bootstrap](http://getbootstrap.com)*. Bootstrap v2 did include [a **separate, unrelated** typeahead implementation](http://getbootstrap.com/2.3.2/javascript.html#typeahead), but to my knowledge the two don't have any code in common with each other (and Bootstrap v3 no longer includes any typeahead widget).

For the sake of accuracy and to prevent confusion, would you mind renaming this project so that "bootstrap" isn't in the name? (Perhaps to something like "twitter-typeahead-rails" or "typeahead-js-rails")

**Comment by Nerian** [comment]
Looks like someone took care of it :)

https://github.com/yourabi/twitter-typeahead-rails

**Comment by cvrebert** [comment]
Well, those were just examples :-) Anything without "bootstrap" will do.
